FROM ghcr.io/tenstorrent/tt-metal/tt-metalium/ubuntu-22.04-dev-amd64:c24b483e46661253b90290a5d8ad13cabdbff26e

WORKDIR /workspace
COPY . .

RUN python3 -m pip install -r tt_metal/python_env/requirements-dev.txt
ENV PYTHONPATH=/workspace
ENV TT_METAL_HOME=/workspace
CMD ["python3", "models/tt_transformers/demo/simple_text_demo.py"]
